### PR TITLE
Nix `Primitives.cs` - types now defined in main repo

### PR DESCRIPTION
**Pull request by Centril**
## Description of Changes

These types have been moved to the main repo, where they are used by bindings-csharp as well.

## Requires SpacetimeDB PRs

- https://github.com/clockworklabs/SpacetimeDB/pull/1477

### CODE REVIEW

**Review by kazimuth — APPROVED** [review]
👍 This would fix our master build issues.

**Comment by bfops** [comment]
It looks like the tests are failing. I get this locally as well:
```
$ dotnet test
  Determining projects to restore...
  Restored /mnt/nutera/work/spacetimedb-csharp-sdk/examples/quickstart/client/client.csproj (in 869 ms).
  Restored /mnt/nutera/work/spacetimedb-csharp-sdk/SpacetimeDB.ClientSDK.csproj (in 869 ms).
  Restored /mnt/nutera/work/spacetimedb-csharp-sdk/tests/tests.csproj (in 878 ms).
CSC : warning CS8785: Generator 'Type' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Could not resolve type U128'. [/mnt/nutera/work/spacetimedb-csharp-sdk/SpacetimeDB.ClientSDK.csproj]
/mnt/nutera/work/spacetimedb-csharp-sdk/src/SpacetimeDB/ClientApi/EnergyQuanta.cs(20,10): error CS0246: The type or namespace name 'U128' could not be found (are you missing a using directive or an assembly reference?) [/mnt/nutera/work/spacetimedb-csharp-sdk/SpacetimeDB.ClientSDK.csproj]
```

**Comment by RReverser** [comment]
I think it's because this repo references 0.11 https://github.com/clockworklabs/spacetimedb-csharp-sdk/blob/fb0cd6ba2ac096dd58226146fe6a5e7bbeb86bea/SpacetimeDB.ClientSDK.csproj#L25 but SpacetimeDB master already set version for C# deps to 0.12. https://github.com/clockworklabs/SpacetimeDB/blob/01d4ed163f90b3fffbba34b3fee5c715b48b4144/crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj#L5

**Comment by bfops** [comment]
> I think it's because this repo references 0.11
> 
> https://github.com/clockworklabs/spacetimedb-csharp-sdk/blob/fb0cd6ba2ac096dd58226146fe6a5e7bbeb86bea/SpacetimeDB.ClientSDK.csproj#L25
> 
> but SpacetimeDB master already set version for C# deps to 0.12. https://github.com/clockworklabs/SpacetimeDB/blob/01d4ed163f90b3fffbba34b3fee5c715b48b4144/crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj#L5

Ah yeah good catch. Ideally we would've bumped these versions when we merged the original breaking PRs but :melting_face:

**Comment by RReverser** [comment]
Ok now only genuine tests are failing. I'll try to fix those up too. cc @Centril

**Review by RReverser — APPROVED** [review]

**Pull request merged**
